[package]
name = "PancakeSmartChef"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "2a458b5ffaaf6a9de6fac679a53912c0be9fe217" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "2a458b5ffaaf6a9de6fac679a53912c0be9fe217" }
PancakePhantomTypes = { local = "../pancake-phantom-types" }

[addresses]
pancake = "fd1d8a523f1be89277ac0787ae3469312667e3d0b3f75a5f01bfc95530a2dc91"
pancake_smart_chef_dev = "db879227e7075058e263d6957bb40ca3f4e5f66ea0691f723c5b9095d9cae253"
pancake_smart_chef_default_admin = "db879227e7075058e263d6957bb40ca3f4e5f66ea0691f723c5b9095d9cae253"
test_coin = "0x16"
